pygments: true

title : Jander.me
url : http://jander.me
author :
  name : James Andersen
  github : jamesandersen
  twitter : jandersen78
  
exclude:
  - bower_components
  - bower.json
  - Gruntfile.js
  - node_modules
  - Gemfile
  - travis.yml
  - config.rb
  - package.json
  - CNAME